server:
  port: 8080

springdoc:
  swagger-ui:
    path: /swagger-ui.html

spring:
  data:
    redis:
      host: localhost
      port: 6379
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: qod-processors
      auto-offset-reset: earliest
      # =======================================================
      # == THE DEFINITIVE FIX: USE A SIMPLE STRING DESERIALIZER ==
      # == This perfectly matches our listener which expects a ==
      # == ConsumerRecord<String, String>.                     ==
      # =======================================================
      key-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      value-deserializer: org.apache.kafka.common.serialization.StringDeserializer
      # All the complex JsonDeserializer properties have been removed.
    producer:
      key-serializer: org.apache.kafka.common.serialization.StringSerializer
      # The producer correctly uses JsonSerializer to convert the SessionInfo object to a JSON string.
      value-serializer: org.springframework.kafka.support.serializer.JsonSerializer

qod:
  topics:
    session-request: qod-session-requests
    session-delete: qod-session-deletions

management:
  endpoints:
    web:
      exposure:
        include: health, info
  endpoint:
    health:
      probes:
        enabled: true
  health:
    readiness-state:
      enabled: true
    liveness-state:
      enabled: true
