# Zookeeper StatefulSet and Service
apiVersion: v1
kind: Service
metadata:
  name: zookeeper
  namespace: qod
spec:
  selector:
    app: zookeeper
  ports:
  - port: 2181
    name: client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: zookeeper
  namespace: qod
spec:
  serviceName: "zookeeper"
  replicas: 1
  selector:
    matchLabels:
      app: zookeeper
  template:
    metadata:
      labels:
        app: zookeeper
    spec:
      containers:
      - name: zookeeper
        image: confluentinc/cp-zookeeper:7.3.0
        ports:
        - containerPort: 2181
          name: client
        env:
        - name: ZOOKEEPER_CLIENT_PORT
          value: "2181"
        - name: ZOOKEEPER_TICK_TIME
          value: "2000"
---
# Kafka StatefulSet and Service
apiVersion: v1
kind: Service
metadata:
  name: kafka
  namespace: qod
spec:
  selector:
    app: kafka
  ports:
  - port: 9092
    name: client
---
apiVersion: apps/v1
kind: StatefulSet
metadata:
  name: kafka
  namespace: qod
spec:
  serviceName: "kafka"
  replicas: 1
  selector:
    matchLabels:
      app: kafka
  template:
    metadata:
      labels:
        app: kafka
    spec:
      # =======================================================
      # == THE DEFINITIVE FIX: Disable Service Links         ==
      # == This prevents Kubernetes from injecting           ==
      # == conflicting KAFKA_PORT environment variables.     ==
      # =======================================================
      enableServiceLinks: false
      initContainers:
      - name: wait-for-zookeeper
        image: busybox:1.36
        command: ['sh', '-c', "echo 'Waiting for Zookeeper...'; until nc -vz zookeeper 2181; do sleep 2; done;"]
      containers:
      - name: kafka
        image: confluentinc/cp-kafka:7.3.0
        ports:
        - containerPort: 9092
          name: client
        env:
        # These variables will now be the ONLY ones used by the container's entrypoint
        - name: KAFKA_BROKER_ID
          value: "1"
        - name: KAFKA_ZOOKEEPER_CONNECT
          value: "zookeeper:2181"
        - name: KAFKA_ADVERTISED_LISTENERS
          value: "PLAINTEXT://kafka:9092"
        - name: KAFKA_LISTENERS
          value: "PLAINTEXT://0.0.0.0:9092"
        - name: KAFKA_LISTENER_SECURITY_PROTOCOL_MAP
          value: "PLAINTEXT:PLAINTEXT"
        - name: KAFKA_OFFSETS_TOPIC_REPLICATION_FACTOR
          value: "1"
        - name: KAFKA_AUTO_CREATE_TOPICS_ENABLE
          value: "true"
        - name: KAFKA_HEAP_OPTS
          value: "-Xmx256m -Xms256m"
