apiVersion: networking.k8s.io/v1
kind: NetworkPolicy
metadata:
  name: qod-default-policy
  namespace: qod
spec:
  # Apply this policy to all pods in the 'qod' namespace
  podSelector: {}
  policyTypes:
    - Ingress
    - Egress
  # --- INGRESS RULES ---
  ingress:
    # Rule 1: Allow traffic FROM any pod within our own 'qod' namespace
    - from:
      - podSelector: {}
    # =======================================================
    # == THE DEFINITIVE FIX: ALLOW TRAFFIC FROM THE INGRESS ==
    # == CONTROLLER'S NAMESPACE.                           ==
    # =======================================================
    # Rule 2: Allow traffic FROM the Ingress Controller namespace
    - from:
      - namespaceSelector:
          matchLabels:
            # IMPORTANT: Change 'ingress-nginx' to whatever namespace you
            # found in the previous step if it's different.
            kubernetes.io/metadata.name: ingress-nginx
  # --- EGRESS RULES ---
  egress:
    # Allow traffic TO any pod within our own 'qod' namespace
    - to:
      - podSelector: {}
    # Allow DNS queries
    - to:
      - namespaceSelector: {}
        podSelector:
          matchLabels:
            k8s-app: kube-dns
      ports:
        - protocol: UDP
          port: 53
    # Allow egress to the internet
    - to:
      - ipBlock:
          cidr: 0.0.0.0/0
